export * from './schema';
export { defaultTheme } from './default-theme';
export { LEGAL_DEFAULTS, type LegalDocDefault } from './legal-defaults';
export { themeToCss } from './css-vars';
export { slugify, productSlug, parseProductSlug } from './slug';
export { googleFontsHrefs } from './google-fonts';
export {
  REQUEST_FORMS,
  requestFormFor,
  requestAnswersToText,
  type RequestField,
  type RequestFieldType,
  type RequestForm,
} from './request-fields';
export {
  UNIDADES,
  UNIDADES_POR_CATEGORIA,
  unidadesDe,
  unidadPorDefectoDe,
  formatearCantidad,
  esUnidadDeTiempo,
  precioEnUnidad,
  unidadesEquivalentes,
  etiquetaPrecio,
  unidadDeCarrito,
  claveDeCarrito,
  precioPeriodoCarrito,
  unidadDeCobro,
  type UnidadServicio,
} from './service-units';
export {
  ATRIBUTOS_POR_CATEGORIA,
  atributosDe,
  numeroDe,
  desajustes,
  fichaDe,
  type AtributoProducto,
  type Desajuste,
} from './product-attributes';
export { MARKETPLACE_ACTIVO } from './marketplace';
export { NEWSLETTER_ACTIVO, CRM_ACTIVO } from './newsletter';
export {
  MODULOS_ADMIN,
  MODULOS_VISIBLES,
  MODULOS_META,
  ROLES_ADMIN,
  ROL_POR_DEFECTO,
  rolDeAdmin,
  esModuloOculto,
  puedeVer,
  modulosDe,
  // Permisos editables desde el panel (overrides guardados en BD).
  MODULOS_OBLIGATORIOS,
  ROLES_FIJOS,
  esRolFijo,
  normalizarModulos,
  modulosEfectivos,
  puedeVerCon,
  type PermisosOverride,
  type ModuloAdmin,
  type RolAdmin,
  type DefinicionRol,
} from './admin-roles';
export {
  COTIZADOR_TIPOS,
  COTIZADORES_META,
  PASOS_MAQUINARIA,
  PASOS_TRITURADOS,
  catalogoCotizadorSchema,
  catalogoMaquinariaSchema,
  catalogoTrituradosSchema,
  partidaMaquinariaSchema,
  partidaTrituradosSchema,
  opcionesCotizadorSchema,
  esCotizadorTipo,
  pasosDe,
  partidasPorProveedor,
  analizarPartidas,
  renglonesDe,
  ligarProducto,
  lineaDeServicio,
  LINEA_MAQUINARIA,
  LINEA_TRANSPORTE,
  LINEA_TRITURADOS,
  type PartidaAnalizada,
  type RenglonTabulador,
  tierDe,
  equipoDe,
  servicioDe,
  productoDe,
  zonaDe,
  precioZona,
  calcularEquipo,
  calcularMaquinaria,
  calcularTriturados,
  calcularCotizacion,
  tieneImporte,
  type CotizadorTipo,
  type CatalogoCotizador,
  type CatalogoMaquinaria,
  type CatalogoTriturados,
  type EmpresaCotizador,
  type FirmaCotizador,
  type BloqueCondiciones,
  type TierTarifa,
  type EquipoCotizador,
  type ServicioCotizador,
  type ProductoTriturado,
  type ZonaTriturado,
  type PartidaCotizador,
  type PartidaMaquinaria,
  type PartidaTriturados,
  type OpcionesCotizador,
  type RenglonCotizacion,
  type CalculoCotizacion,
  type PasoCotizador,
} from './quoter';
export {
  CATALOGOS_DEFAULT,
  CATALOGO_MAQUINARIA_DEFAULT,
  CATALOGO_TRITURADOS_DEFAULT,
} from './quoter-defaults';
